const sportService = {
    sports: [
        {sport: "Golf"},
        {sport: "Tennis"},
        {sport: "Cricket"},
        {sport: "Basketball"},
        {sport: "Baseball"},
        {sport: "American Football"},
        {sport: "Aquatics"},
        {sport: "Archery"},
        {sport: "Automobile Racing"},
        {sport: "Badminton"},
        {sport: "Beach Volleyball"},
        {sport: "Bobsleigh"},
        {sport: "Body Building"},
        {sport: "Boxing"},
        {sport: "Cross Country Running"},
        {sport: "Cross Country Skiing"},
        {sport: "Curling"},
        {sport: "Cycling"},
        {sport: "Darts"},
        {sport: "Decathlon"},
        {sport: "Down Hill Skiing"},
        {sport: "Equestrianism"},
        {sport: "eSports"},
        {sport: "Fencing"},
        {sport: "Field Hockey"},
        {sport: "Figure Skating"},
        {sport: "Gymnastics"},
        {sport: "Ice Hockey"},
        {sport: "Martial Arts"},
        {sport: "Mixed Martial Arts"},
        {sport: "Modern Pentathlon"},
        {sport: "Motorcycle Racing"},
        {sport: "Netball"},
        {sport: "Polo"},
        {sport: "Racquetball"},
        {sport: "Rowing"},
        {sport: "Rugby"},
        {sport: "Sailing"},
        {sport: "Softball"},
        {sport: "Shooting"},
        {sport: "Skateboarding"},
        {sport: "Skeet Shooting"},
        {sport: "Skeleton"},
        {sport: "Snow Boarding"},
        {sport: "Soccer (Football)"},
        {sport: "Squash"},
        {sport: "Surfing"},
        {sport: "Swimming"},
        {sport: "Track and Field"}
    ]
};

export default sportService;